sonar.projectKey=fitforge-nutri-service
sonar.projectName=fitforge-nutri-service
sonar.sources=.
sonar.exclusions=**/target/**, **/build/**, **/dist/**, **/node_modules/**

sonar.sourceEncoding=UTF-8
